Euro_Golf/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('main.urls')),
    path('admin/', admin.site.urls),
]

main/urls.py
from django.urls import include, path
from main.views import show_main, create_product, show_xml, show_json, show_xml_by_id, show_json_by_id, delete_product, register, login_user, logout_user, add_stock, subtract_stock, edit_product, pricelist_view, graphite_view, steel_view, get_product_json, add_product_ajax, delete_product_ajax, create_product_flutter

app_name = 'main'

urlpatterns = [
    path('', show_main, name='show_main'),
    path('pricelist/', pricelist_view, name='pricelist'),
    path('steel/', steel_view, name='steel_view'),
    path('graphite/', graphite_view, name='graphite_view'),
    path('create-product', create_product, name='create_product'),
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'),
    path('xml/<int:id>/', show_xml_by_id, name='show_xml_by_id'),
    path('json/<int:id>/', show_json_by_id, name='show_json_by_id'),
    path('delete_product/<int:id>/', delete_product, name='delete_product'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('add_stock/<int:product_id>/', add_stock, name='add_stock'),
    path('subtract_stock/<int:product_id>/', subtract_stock, name='subtract_stock'),
    path('edit-product/<int:id>', edit_product, name='edit_product'),
    path('get_product_json/', get_product_json, name='get_product_json'),
    path('create-product-ajax/', add_product_ajax, name='add_product_ajax'),
    path('delete-product-ajax/<int:id>/', delete_product_ajax, name='delete_product_ajax'),
    path('auth/', include('authentication.urls')),
    path('create-flutter/', create_product_flutter, name='create_product_flutter'),
]

main/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Product(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    price = models.IntegerField()
    amount = models.PositiveIntegerField(default=0)
    category = models.TextField()
    description = models.TextField()
    date_added = models.DateField(auto_now_add=True)

main/forms.py
from django.forms import ModelForm
from main.models import Product

class ProductForm(ModelForm):
    class Meta:
        model = Product
        fields = ["name", "price", "amount","category", "description"]

main/views.py
import json
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponseRedirect, HttpResponseNotFound, JsonResponse
from main.forms import ProductForm
from django.http import HttpResponse
from django.core import serializers
from django.urls import reverse
from main.models import Product
from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages  
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
import datetime
from django.views.decorators.csrf import csrf_exempt

# Create your views here.
@login_required(login_url='/login')
def show_main(request):
    products = Product.objects.filter(user=request.user)
    count_item = products.count()
    context = {
        'name': request.user.username,
        'class': 'PBP E', 
        'products': products,
        'count_item': count_item,
        'last_login': request.COOKIES['last_login'],
    }
    return render(request, "main.html", context)

@csrf_exempt
def create_product_flutter(request):
    if request.method == 'POST':
        
        data = json.loads(request.body)

        new_product = Product.objects.create(
            user = request.user,
            name = data["name"],
            price = int(data["price"]),
            amount = int(data["amount"]),
            category = data["category"],
            description = data["description"]
        )

        new_product.save()

        return JsonResponse({"status": "success"}, status=200)
    else:
        return JsonResponse({"status": "error"}, status=401)

def pricelist_view(request):
    products = []
    return render(request, 'pricelist.html', {'products': products})

def steel_view(request):
    products = []
    return render(request, 'steel.html', {'products': products})

def graphite_view(request):
    products = []
    return render(request, 'graphite.html', {'products': products})

def create_product(request):
    form = ProductForm(request.POST or None)

    if form.is_valid() and request.method == "POST":
        product = form.save(commit=False)
        product.user = request.user
        product.save()
        return HttpResponseRedirect(reverse('main:show_main'))

    context = {'form': form}
    return render(request, "create_product.html", context)

def add_stock(request, product_id):
    product = get_object_or_404(Product, id=product_id)
    product.amount += 1
    product.save()
    return redirect('main:show_main')

def subtract_stock(request, product_id):
    product = get_object_or_404(Product, id=product_id)
    if product.amount > 0:
        product.amount -= 1
        product.save()
    return redirect('main:show_main')

def show_xml(request):
    data = Product.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
    data = Product.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_xml_by_id(request, id):
    data = Product.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json_by_id(request, id):
    data = Product.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def delete_product(request, id):
    product = get_object_or_404(Product, pk=id)

    if request.method == 'POST':
        product.delete()
        return redirect('main:show_main')
    
    return render(request, 'delete_product.html', {'product': product})

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your account has been successfully created!')
            return redirect('main:login')
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            response = HttpResponseRedirect(reverse("main:show_main")) 
            response.set_cookie('last_login', str(datetime.datetime.now()))
            return response
        else:
            messages.info(request, 'Sorry, incorrect username or password. Please try again.')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('main:login'))
    response.delete_cookie('last_login')
    return response

def edit_product(request, id):
    product = Product.objects.get(pk = id)
    form = ProductForm(request.POST or None, instance=product)

    if form.is_valid() and request.method == "POST":
        form.save()
        return HttpResponseRedirect(reverse('main:show_main'))

    context = {'form': form}
    return render(request, "edit_product.html", context)

def get_product_json(request):
    product_item = Product.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize('json', product_item))

@csrf_exempt
def add_product_ajax(request):
    if request.method == 'POST':
        name = request.POST.get("name")
        price = request.POST.get("price")
        amount = request.POST.get("amount")
        category = request.POST.get("category")
        description = request.POST.get("description")
        user = request.user

        new_product = Product(name=name, price=price, amount=amount, category=category, description=description, user=user)
        new_product.save()

        return HttpResponse(b"CREATED", status=201)
    
    return HttpResponseNotFound()

@csrf_exempt
def delete_product_ajax(request, id):
    product = get_object_or_404(Product, pk=id)

    if request.method == 'POST':
        product.delete()
        return HttpResponseRedirect(reverse('main:show_main'))
    return HttpResponseNotFound

main/templates/create_product.html
{% extends 'base.html' %} 

{% block content %}
<h1>Add New Product</h1>

<form method="POST">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
        <tr>
            <td></td>
            <td>
                <a href="{% url 'main:show_main' %}">Cancel</a>
                <input type="submit" value="Add Product"/>
            </td>
        </tr>
    </table>
</form>

{% endblock %}

main/templates/edit_product.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

<div class="add-product-container">
    <h1>Edit Product</h1>

    <form method="POST">
        {% csrf_token %}
        <div class="form-container">
            <table>
                {{ form.as_table }}
            </table>
        </div>
        <div class="button-container">
            <a href="{% url 'main:show_main' %}">
                <button type="button" class="cancel-button">
                    Cancel
                </button>
            </a>
            <input type="submit" value="Edit Product" class="add-button" />
        </div>
    </form>
</div>

{% endblock %}

main/templates/graphite.html
{% extends 'base.html' %}

{% block content %}
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
        <a class="navbar-brand" href="#">Euro Golf</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'main:show_main' %}">Home</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    Info
                </a>
                <ul class="dropdown-menu">
                    <li><a class="dropdown-item" href="{% url 'main:pricelist' %}">Pricelist</a></li>
                    <li class="dropdown-divider"></li>
                    <li><a class="dropdown-item" href="{% url 'main:steel_view' %}">Steel Shaft</a></li>
                    <li><a class="dropdown-item" href="{% url 'main:graphite_view' %}">Graphite Shaft</a></li>
                </ul>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'main:logout' %}">Logout</a>
            </li>
            </ul>
            <form class="d-flex" role="search">
            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
        </div>
        </div>
    </nav>
    <div class = "Judul_graphite">
        Graphite Shaft
    </div>
    </br>
    <table class="tabel_graphite">
    <thead>
    <tr>
        <th class="tg-0lax">Name</th>
        <th class="tg-0lax">Image</th>
        <th class="tg-0lax">Price</th>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td class="tg-0lax">Fujikura Axiom 125</td>
        <td class="tg-0lax"><img src="https://golfshaftsamerica.com/cdn/shop/products/Axiom_105_1024x1024.jpg?v=1677120576" width="150" height="108"/></td>
        <td class="tg-0lax">Rp 12.500.000,00</td>
    </tr>
    <tr>
        <td class="tg-0lax">Mitsubishi Chemical Taper</td>
        <td class="tg-0lax"><img src="https://www.tourspecgolf.com/media/catalog/product/m/i/mitsubishi_chemical_mmt_taper_iron_shaft_1.jpg" width="150" height="108"/></td>
        <td class="tg-0lax">Rp 10.500.000,00</td>
    </tr>
    <tr>
        <td class="tg-0lax">Aerotech SteelFiber i110</td>
        <td class="tg-0lax"><img src="https://m.media-amazon.com/images/I/51J9rTWfJBL._AC_UF1000,1000_QL80_.jpg" width="150" height="108"/></td>
        <td class="tg-0lax">Rp 6.300.000,00</td>
    </tr>
    <tr>
        <td class="tg-0lax">Mitsubishi C6 80</td>
        <td class="tg-0lax"><img src="https://m.media-amazon.com/images/I/31J9Gafqz8L._AC_UF1000,1000_QL80_.jpg" width="150" height="108"/></td>
        <td class="tg-0lax">Rp 6.200.000,00</td>
    </tr>
    </tbody>
    </table>
    </br>
    <marquee behavior="scroll" direction="right" style= "color: blueviolet;">
        Welcome to Euro Golf! 
    </marquee>
{% endblock content %}

main/templates/login.html
{% extends 'base.html' %}

{% block meta %}
{% endblock meta %}

{% block content %}
<div class="login-container">
    <div class="login">
        <form method="POST" action="">
            {% csrf_token %}
            <table>
                <tr>
                    <td>Username: </td>
                    <td><input type="text" name="username" placeholder="Username" class="form-control"></td>
                </tr>
                        
                <tr>
                    <td>Password: </td>
                    <td><input type="password" name="password" placeholder="Password" class="form-control"></td>
                </tr>

                <tr>
                    <td></td>
                    <td><input class="btn login-btn" type="submit" value="Login"></td>
                </tr>
            </table>
        </form>

        {% if messages %}
            <ul class="error-messages">
                {% for message in messages %}
                    <li>{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}     
        
        <div class="register">
            Don't have an account yet? <a href="{% url 'main:register' %}">Register Now</a>
        </div>
    </div>

    <a href="#"><img src="https://eurogolf-liege.be/wp-content/themes/eurogolf/img/logo-eurogolf.png" width="800" height="550" alt="Euro Golf Logo"></a>
</div>
{% endblock content %}

main/templates/main.html
{% extends 'base.html' %}

{% block content %}
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
        <a class="navbar-brand" href="#">Euro Golf</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'main:show_main' %}">Home</a>
            </li>
            <li class="new_product">
                <a class="nav-link" href="{% url 'main:create_product' %}">Add New Product</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    Info
                </a>
                <ul class="dropdown-menu">
                    <li><a class="dropdown-item" href="{% url 'main:pricelist' %}">Pricelist</a></li>
                    <li class="dropdown-divider"></li>
                    <li><a class="dropdown-item" href="{% url 'main:steel_view' %}">Steel Shaft</a></li>
                    <li><a class="dropdown-item" href="{% url 'main:graphite_view' %}">Graphite Shaft</a></li>
                </ul>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'main:logout' %}">Logout</a>
            </li>
            </ul>
            <form class="d-flex" role="search">
            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
        </div>
        </div>
    </nav>

    </br>

    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="exampleModalLabel">Add New Product</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <form id="form" onsubmit="return false;">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name" class="col-form-label">Name:</label>
                            <input type="text" class="form-control" id="name" name="name"></input>
                        </div>
                        <div class="mb-3">
                            <label for="price" class="col-form-label">Price:</label>
                            <input type="number" class="form-control" id="price" name="price"></input>
                        </div>
                        <div class="mb-3">
                            <label for="amount" class="col-form-label">Amount:</label>
                            <input type="number" class="form-control" id="amount" name="amount"></input>
                        </div>
                        <div class="mb-3">
                            <label for="category" class="col-form-label">Category:</label>
                            <textarea class="form-control" id="category" name="category"></textarea>
                        </div>
                        <div class="mb-3">
                            <label for="description" class="col-form-label">Description:</label>
                            <textarea class="form-control" id="description" name="description"></textarea>
                        </div>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary" id="button_add" data-bs-dismiss="modal">Add Product</button>
                </div>
            </div>
        </div>
    </div>

    <div class="container">
        <div class="row" id="product_card_row"></div>
    </div>
      
    <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal" style="margin-bottom: 20px;">Add Product by AJAX</button>

    <div class="info_login">
    <h7>Total item yang dimasukkan: {{ count_item }}</h7>
    <h7>Sesi terakhir login: {{ last_login }}</h7>
    </div>
    
    <div class="marquee">
    <marquee behavior="scroll" direction="right">Welcome to Euro Golf!</marquee>
    </div>
      
    <script>
        async function getProducts() {
          return fetch("{% url 'main:get_product_json' %}").then((res) => res.json());
        }
      
        async function deleteProduct(productId) {
          try {
            const response = await fetch("{% url 'main:delete_product_ajax' 0 %}".replace('0', productId), {
              method: 'POST',
            });
      
            if (response.ok) {
              refreshProducts();
            } else {
              console.error('Gagal menghapus produk.');
            }
          } catch (error) {
            console.error('Terjadi kesalahan:', error);
          }
        }
      
        async function refreshProducts() {
            const products = await getProducts();
            const productCardRow = document.getElementById("product_card_row");
            productCardRow.innerHTML = "";

            products.forEach((item, index) => {
                if (index % 3 === 0) {
                    const cardRow = document.createElement("div");
                    cardRow.classList.add("row");
                    productCardRow.appendChild(cardRow);
                }

                const cardCol = document.createElement("div");
                cardCol.classList.add("col-md-4"); 
                cardCol.innerHTML = `
                <div class="card mb-3 bg-dark text-white">
                    <div class="card-body">
                    <h5 class="card-title">${item.fields.name}</h5>
                    <p class="card-text">Price: ${item.fields.price}</p>
                    <p class="card-text">Amount: ${item.fields.amount}</p>
                    <p class="card-text">Category: ${item.fields.category}</p>
                    <p class="card-text">Description: ${item.fields.description}</p>
                    <p class="card-text">Date Added: ${item.fields.date_added}</p>
                    <a href="add_stock/${item.pk}" class="btn btn-sm btn-secondary">+</a>
                    <a href="subtract_stock/${item.pk}" class="btn btn-sm btn-secondary">-</a>
                    <a href="edit-product/${item.pk}" class="btn btn-sm btn-primary">Edit</a>
                    <a onclick="deleteProduct(${item.pk})" class="btn btn-sm btn-danger">Delete</a>
                    </div>
                </div>
                `;

                const cardRow = productCardRow.lastChild;
                cardRow.appendChild(cardCol);
            });
        }

        function addProduct() {
            fetch("{% url 'main:add_product_ajax' %}", {
                method: "POST",
                body: new FormData(document.querySelector('#form'))
            }).then(refreshProducts)

            document.getElementById("form").reset()
            return false
        }
      
        document.getElementById("button_add").onclick = addProduct;
        refreshProducts();
      </script>
{% endblock content %}

main/templates/pricelist.html
{% extends 'base.html' %}

{% block content %}
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
        <a class="navbar-brand" href="#">Euro Golf</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'main:show_main' %}">Home</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    Info
                </a>
                <ul class="dropdown-menu">
                    <li><a class="dropdown-item" href="{% url 'main:pricelist' %}">Pricelist</a></li>
                    <li class="dropdown-divider"></li>
                    <li><a class="dropdown-item" href="{% url 'main:steel_view' %}">Steel Shaft</a></li>
                    <li><a class="dropdown-item" href="{% url 'main:graphite_view' %}">Graphite Shaft</a></li>
                </ul>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'main:logout' %}">Logout</a>
            </li>
            </ul>
            <form class="d-flex" role="search">
            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
        </div>
        </div>
    </nav>
    <div class = "Judul_pricelist">
        Pricelist
    </div>
    </br>
    <table class="tabel_pricelist">
    <thead>
    <tr>
        <th class="tg-0lax">Name</th>
        <th class="tg-0lax">Image</th>
        <th class="tg-0lax">Shaft Type</th>
        <th class="tg-0lax">Price</th>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td class="tg-0lax">TaylorMade P790</td>
        <td class="tg-0lax"><img src="https://www.taylormadegolf.com/dw/image/v2/AAIS_PRD/on/demandware.static/-/Sites-tmag-master-catalog/en_US/v1694491595824/zoom/TA283_zoom_D.jpg?sw=900&sh=900&sm=fit" width="150" height="108"/></td>
        <td class="tg-0lax">Graphite</td>
        <td class="tg-0lax">Rp 23.500.000,00</td>
    </tr>
    <tr>
        <td class="tg-0lax">TaylorMade P790</td>
        <td class="tg-0lax"><img src="https://www.taylormadegolf.com/dw/image/v2/AAIS_PRD/on/demandware.static/-/Sites-tmag-master-catalog/en_US/v1694491595824/zoom/TA283_zoom_D.jpg?sw=900&sh=900&sm=fit" width="150" height="108"/></td>
        <td class="tg-0lax">Steel</td>
        <td class="tg-0lax">Rp 21.750.000,00</td>
    </tr>
    <tr>
        <td class="tg-0lax">TaylorMade P7MC</td>
        <td class="tg-0lax"><img src="https://www.taylormadegolf.com/dw/image/v2/AAIS_PRD/on/demandware.static/-/Sites-tmag-master-catalog/en_US/v1671080791923/zoom/TA239_zoom_D.jpg?sw=400&sh=400&sm=fit" width="150" height="108"/></td>
        <td class="tg-0lax">Steel</td>
        <td class="tg-0lax">Rp 20.000.000,00</td>
    </tr>
    <tr>
        <td class="tg-0lax">Mizuno JPX 923</td>
        <td class="tg-0lax"><img src="https://mizunogolf.com/wp-content/themes/mizunotheme2015/images/jpx923/gallery/923forged-modal-gal1-img1.jpg" width="150" height="108"/></td>
        <td class="tg-0lax">Steel</td>
        <td class="tg-0lax">Rp 20.150.000,00</td>
    </tr>
    </tbody>
    </table>
    </br>
    <marquee behavior="scroll" direction="right" style= "color: blueviolet;">
        Welcome to Euro Golf! 
    </marquee>
{% endblock content %}

main/templates/register.html
{% extends 'base.html' %}

{% block meta %}
    <title>Register</title>
{% endblock meta %}

{% block content %}  

<div class = "login">
    
    <h1>Register</h1>  

        <form method="POST" >  
            {% csrf_token %}  
            <table>  
                {{ form.as_table }}  
                <tr>  
                    <td></td>
                    <td><input type="submit" name="submit" value="Daftar"/></td>  
                </tr>  
            </table>  
        </form>

    {% if messages %}  
        <ul>   
            {% for message in messages %}  
                <li>{{ message }}</li>  
                {% endfor %}  
        </ul>   
    {% endif %}

</div>  

{% endblock content %}

main/templates/steel.html
{% extends 'base.html' %}

{% block content %}
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
        <a class="navbar-brand" href="#">Euro Golf</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'main:show_main' %}">Home</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    Info
                </a>
                <ul class="dropdown-menu">
                    <li><a class="dropdown-item" href="{% url 'main:pricelist' %}">Pricelist</a></li>
                    <li class="dropdown-divider"></li>
                    <li><a class="dropdown-item" href="{% url 'main:steel_view' %}">Steel Shaft</a></li>
                    <li><a class="dropdown-item" href="{% url 'main:graphite_view' %}">Graphite Shaft</a></li>
                </ul>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'main:logout' %}">Logout</a>
            </li>
            </ul>
            <form class="d-flex" role="search">
            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
        </div>
        </div>
    </nav>
    <div class = "Judul_steel">
        Steel Shaft
    </div>
    </br>
    <table class="tabel_steel">
    <thead>
    <tr>
        <th class="tg-0lax">Name</th>
        <th class="tg-0lax">Image</th>
        <th class="tg-0lax">Price</th>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td class="tg-0lax">Dynamic Gold X7</td>
        <td class="tg-0lax"><img src="https://www.truetempersports.com/en-us/media/catalog/product/d/y/dynamicgold_x7_hero.png?quality=80&fit=bounds&height=700&width=700&canvas=700:700" width="150" height="108"/></td>
        <td class="tg-0lax">Rp 5.500.000,00</td>
    </tr>
    <tr>
        <td class="tg-0lax">KBS C-TAPER</td>
        <td class="tg-0lax"><img src="https://kbsgolfshafts.com/wp-content/uploads/2023/02/kbs_ctaper_110_r_d.png" width="150" height="108"/></td>
        <td class="tg-0lax">Rp 5.500.000,00</td>
    </tr>
    <tr>
        <td class="tg-0lax">UST Recoil 110</td>
        <td class="tg-0lax"><img src="https://www.alphagolfclubs.com/cdn/shop/products/iron-recoil_5b0759b9-a4a4-4860-85a5-872852067447_700x700.jpg?v=1649178924" width="150" height="108"/></td>
        <td class="tg-0lax">Rp 6.000.000,00</td>
    </tr>
    <tr>
        <td class="tg-0lax">Project X Steel</td>
        <td class="tg-0lax"><img src="https://www.truetempersports.com/en-us/golf/media/catalog/product/p/r/projectx_hero.png?quality=80&fit=bounds&height=700&width=700&canvas=700:700" width="150" height="108"/></td>
        <td class="tg-0lax">Rp 5.500.000,00</td>
    </tr>
    </tbody>
    </table>
    </br>
    <marquee behavior="scroll" direction="right" style= "color: blueviolet;">
        Welcome to Euro Golf! 
    </marquee>
{% endblock content %}